spring:
  application:
    name: assetmanagement
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  #  pagination:
  #    size: 6
  security:
    jwt:
      secret-key: b7915faf4bedf5f50529aa2f564ff09cdcab8ec85ce654a897fe32afd65e0fe6
      expiration: 86400000 #one day
      refresh-token:
        expiration: 604800000 #one week
  cors:
    originPatterns: http://127.0.0.1:5173*,http://localhost:5173*
  cookie:
    name: asset-management-server
    max-age: 604800 #one week
    path: /
    same-site: Lax
    http-only: true
    secure: false


logging:
  level:
    org:
      springframework:
        security: TRACE
